#vaadin.launch-browser=true
#spring.application.name=SV-TASK

logging:
  level:
    org:
      hibernate:
        SQL: TRACE

      springframework:
        orm:
          jpa: TRACE
          JpaTransactionManager: TRACE


#
#
#
#
#
#  logging.level.org.springframework.orm.jpa=INFO
#  logging.level.org.springframework.transaction=INFO
#  logging.level.org.springframework.transaction.interceptor=TRACE
#  logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

vaadin:
  launch-browser: true

spring:
  spring:
    application:
      name: SV-TASK
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect